version: '3.4'
###############
##### This docker-compose file is based off of the tig-stack - https://github.com/matisku/tig-stack.git
###############
services:
    grafana:
        image: matisq/grafana:latest
        ports:
            - 5000:3000
        links:
            - influxdb:influxdb
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
            GF_SECURITY_SECRET_KEY: grafana
            GF_USERS_ALLOW_SIGN_UP: "true"
            GF_USERS_ALLOW_ORG_CREATE: "true"
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_ANONYMOUS_ORG_NAME: grafana
            GF_DASHBOARDS_JSON_ENABLED: "true"
            GF_DASHBOARDS_JSON_PATH: /opt/grafana
            GRAFANA_PLUGINS_ENABLED: "false"
        restart: always


    influxdb:
        container_name: influxdb
        image: influxdb:1.7.9
        hostname: influxdb
        volumes:
            - ./influx-data:/var/lib/influxdb
        environment:
            INFLUXDB_DB: "telegraf"
            INFLUXDB_ADMIN_USER: "grafana"
            INFLUXDB_ADMIN_PASSWORD: "grafana"
        ports:
            - 8083:8083
            - 8086:8086
        restart: always


    #
    # influxdb:
    #     image: matisq/influxdb:latest
    #     ports:
    #         - 8083:8083
    #         - 8086:8086
    #     environment:
    #         INFLUX_DATABASE: "telegraf"
    #         INLFUX_ADMIN_USER: "grafana"
    #         INFLUX_ADMIN_PASS: "grafana"
    #
    importer:
        # build: importer
        build: importer-update-test
        volumes:
             - ./importer/credentials/aws:/root/.aws
